## Deliverable 2. Create a Customer Travel Destinations Map.

In [1]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps
import numpy as np

# Import API key
from config import g_key

# Configure gmaps API key
gmaps.configure(api_key=g_key)

In [2]:
# 1. Import the WeatherPy_database.csv file. 
city_data_df = pd.read_csv("C:\\Users\\Lex\\ucb_bootcamp\\MyRepo\\World_Weather_Analysis\\Weather_Database\\WeatherPy_Database.csv")
city_data_df.head()

,City_ID,City,Country,Date,Lat,Lng,Overall Weather,Weather Description,Max Temp,Humidity,Cloudiness,Wind Speed,Rain Inches (last 3 hrs),Snow Inches (last 3 hrs)
0,0,Rikitea,PF,2021-06-25 15:23:06,-23.1203,-134.9692,Clouds,few clouds,74.03,77,14,3.60,0,0
1,1,Bluff,NZ,2021-06-25 15:23:07,-46.6000,168.3333,Clouds,overcast clouds,48.79,91,90,6.33,0,0
2,2,Albany,US,2021-06-25 15:22:40,42.6001,-73.9662,Clouds,overcast clouds,75.61,54,100,4.47,0,0
3,3,Arman,RU,2021-06-25 15:23:07,59.7000,150.1667,Clouds,scattered clouds,48.45,88,45,2.17,0,0
4,4,Mglin,RU,2021-06-25 15:14:51,53.0591,32.8475,Clear,clear sky,87.78,61,9,4.52,0,0

In [3]:
# 2. Prompt the user to enter minimum and maximum temperature criteria 
min_temp = float(input("What is the minimum temperature you would like for your vacation? "))
max_temp = float(input("What is the maximum temperature you would like for your vacation? "))

What is the minimum temperature you would like for your vacation? 75
What is the maximum temperature you would like for your vacation? 90

In [4]:
# 3. Filter the city_data_df DataFrame using the input statements to create a new DataFrame using the loc method.
# Filter the dataset to find the cities that fit the criteria.
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                       (city_data_df["Max Temp"] >= min_temp)]
preferred_cities_df

,City_ID,City,Country,Date,Lat,Lng,Overall Weather,Weather Description,Max Temp,Humidity,Cloudiness,Wind Speed,Rain Inches (last 3 hrs),Snow Inches (last 3 hrs)
2,2,Albany,US,2021-06-25 15:22:40,42.6001,-73.9662,Clouds,overcast clouds,75.61,54,100,4.47,0,0
4,4,Mglin,RU,2021-06-25 15:14:51,53.0591,32.8475,Clear,clear sky,87.78,61,9,4.52,0,0
20,20,Cayenne,GF,2021-06-25 15:23:12,4.9333,-52.3333,Mist,mist,86.09,74,75,5.99,0,0
22,22,Acapulco,MX,2021-06-25 15:23:13,16.8634,-99.8901,Clouds,overcast clouds,75.02,94,90,11.50,0,0
26,26,Lorengau,PG,2021-06-25 15:23:14,-2.0226,147.2712,Clouds,overcast clouds,80.51,79,100,6.02,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
682,682,Montale,IT,2021-06-25 15:26:46,43.9356,11.0171,Clear,clear sky,86.68,44,0,5.01,0,0
683,683,Vanimo,PG,2021-06-25 15:26:47,-2.6741,141.3028,Rain,light rain,77.38,88,82,2.55,0,0
686,686,Sevierville,US,2021-06-25 15:23:23,35.8681,-83.5618,Clear,clear sky,81.79,63,1,4.61,0,0
687,687,Rameswaram,IN,2021-06-25 15:26:48,9.2833,79.3000,Clouds,broken clouds,83.35,78,83,18.32,0,0
688,688,Nago,JP,2021-06-25 15:26:48,26.5881,127.9761,Clouds,few clouds,81.03,88,20,11.92,0,0

In [5]:
# 4a. Determine if there are any empty rows.
preferred_cities_df.isnull().sum()

City_ID                     0
City                        0
Country                     1
Date                        0
Lat                         0
Lng                         0
Overall Weather             0
Weather Description         0
Max Temp                    0
Humidity                    0
Cloudiness                  0
Wind Speed                  0
Rain Inches (last 3 hrs)    0
Snow Inches (last 3 hrs)    0
dtype: int64

In [6]:
# 4b. Drop any empty rows and create a new DataFrame that doesn’t have empty rows.
clean_df = preferred_cities_df.dropna()
clean_df.head()

,City_ID,City,Country,Date,Lat,Lng,Overall Weather,Weather Description,Max Temp,Humidity,Cloudiness,Wind Speed,Rain Inches (last 3 hrs),Snow Inches (last 3 hrs)
2,2,Albany,US,2021-06-25 15:22:40,42.6001,-73.9662,Clouds,overcast clouds,75.61,54,100,4.47,0,0
4,4,Mglin,RU,2021-06-25 15:14:51,53.0591,32.8475,Clear,clear sky,87.78,61,9,4.52,0,0
20,20,Cayenne,GF,2021-06-25 15:23:12,4.9333,-52.3333,Mist,mist,86.09,74,75,5.99,0,0
22,22,Acapulco,MX,2021-06-25 15:23:13,16.8634,-99.8901,Clouds,overcast clouds,75.02,94,90,11.50,0,0
26,26,Lorengau,PG,2021-06-25 15:23:14,-2.0226,147.2712,Clouds,overcast clouds,80.51,79,100,6.02,0,0

In [8]:
# 5a. Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = clean_df[["City", "Country", "Max Temp", "Current Description", "Lat", "Lng"]].copy()

# 5b. Create a new column "Hotel Name"
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

KeyError: "['Current Description'] not in index"

In [ ]:
# 6a. Set parameters to search for hotels with 5000 meters.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

# 6b. Iterate through the hotel DataFrame.
for index, row in hotel_df.iterrows():
    # 6c. Get latitude and longitude from DataFrame
    lat = row["Lat"]
    lng = row["Lng"]
    params["location"] = f"{lat},{lng}"
    # 6d. Set up the base URL for the Google Directions API to get JSON data.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

    # 6e. Make request and retrieve the JSON data from the search. 
    hotels = requests.get(base_url, params=params).json()
    
    # 6f. Get the first hotel from the results and store the name, if a hotel isn't found skip the city.
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels['results'][0]['name']
    
    except (IndexError):
        print("Cannot find hotel...Skipping")

In [ ]:
# 7. Drop the rows where there is no Hotel Name.
clean_hotel_df = hotel_df.loc[(hotel_df["Hotel Name"]!='')]
clean_hotel_df.head()

In [ ]:
# 8a. Create the output File (CSV)
output_data_file = "WeatherPy_vacation.csv"
# 8b. Export the City_Data into a csv
clean_hotel_df.to_csv(output_data_file, index_label="City_ID")

In [ ]:
# 9. Using the template add city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Weather</dt><dd>{Current Description}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""

# 10a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in clean_hotel_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = clean_hotel_df[["Lat", "Lng"]]

In [ ]:
# 11a. Add a marker layer for each city to the map. 
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
# 11b. Display the figure
figs = gmaps.figure(center=(30.0, 31.0), zoom_level=1.4)
fig.add_layer(marker_layer)
fig